name: pre-commit
permissions:
  contents: read

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # v3.0.0
        with:
          extra_args: --all-files
